baseURL = '/'
languageCode = 'en-us'
title = 'Tyler Pham'
theme = "PaperMod"

# Theme configuration
[params]
env = "production"
author = "<author>"
description = "Portfolio description"
keywords = ["Aboutme", "Portfolio", "PaperMod"]
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableScrollToTop = false



[params.profileMode]
enabled = true
title = "Tyler Pham"
subtitle = "Hello, welcome to my portfolio!"
imageUrl = "profile_pic.png"
imageWidth = 120
imageHeight = 120

[markup.goldmark.renderer]
unsafe=true

[[params.socialIcons]]
name = "github"
url = "https://github.com/TylerPham2000"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/tyler-pham-/"

[[menu.main]]
identifier = "blog"
name = "About me"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 20

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 20
