baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Tyler Pham Portfolio'
theme = "PaperMod"

# Theme configuration
[params]
env = "production"
author = "<author>"
description = "Portfolio description"
keywords = ["Aboutme", "Portfolio", "PaperMod"]
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableScrollToTop = false

[params.label]
text = "Home"
icon = "/pic.png"
iconHeight = 24

[params.profileMode]
enabled = true
title = "Tyler pham"
subtitle = "Hello, welcome to my portfolio!"
imageUrl = "pic.png"
imageWidth = 120
imageHeight = 120

[[params.socialIcons]]
name = "github"
url = "https://github.com/TylerPham2000"
GitHub = "xxxx"
Linkedin = "xxxx"
Instagram = "xxxx"
Email   = "xxxx"

[[menu.main]]
identifier = "blog"
name = "About me"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "skills"
name = "Skills"
url = "/skills/"
weight = 20

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 20
